steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/quicklocal-backend:$COMMIT_SHA', 
      '-t', 'gcr.io/$PROJECT_ID/quicklocal-backend:latest',
      '.'
    ]
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quicklocal-backend:$COMMIT_SHA']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quicklocal-backend:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'quicklocal-backend',
      '--image', 'gcr.io/$PROJECT_ID/quicklocal-backend:$COMMIT_SHA',
      '--region', 'asia-south1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '1',
      '--concurrency', '1000',
      '--timeout', '300',
      '--port', '3000',
      '--max-instances', '10'
    ]

images:
  - gcr.io/$PROJECT_ID/quicklocal-backend:$COMMIT_SHA
  - gcr.io/$PROJECT_ID/quicklocal-backend:latest

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
