# Render.com Configuration - Memory Optimized (CORRECTED)
services:
  - type: web
    name: quicklocal-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLUSTER_MODE
        value: false
      - key: MAX_WORKERS
        value: 1
      - key: NODE_OPTIONS
        value: "--max-old-space-size=256 --expose-gc"
      - key: DB_POOL_SIZE
        value: 1
      - key: MEMORY_WARNING_THRESHOLD
        value: 70
      - key: MEMORY_CRITICAL_THRESHOLD
        value: 85
      # CORS Configuration for Production
      - key: CORS_ORIGINS
        value: "https://www.quicklocal.shop,https://quicklocal.shop"
      - key: CLIENT_URL
        value: "https://www.quicklocal.shop"
      - key: API_URL
        value: "https://quicklocal-backend.onrender.com"
      # Database Configuration
      - key: MONGODB_URI
        sync: false  # You'll need to set this in Render dashboard
      # Required for configuration validation
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
    scaling:
      minInstances: 1
      maxInstances: 1
