# render.yaml
services:
  - type: web
    name: ecommerce-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false # Set this in Render dashboard for security
      - key: JWT_SECRET # If you plan to use JWT for authentication
        sync: false
      - key: PORT
        value: 10000