# Render.com Configuration - Memory Optimized (CORRECTED)
services:
  - type: web
    name: quicklocal-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start:render
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLUSTER_MODE
        value: false
      - key: MAX_WORKERS
        value: 1
      - key: NODE_OPTIONS
        value: "--max-old-space-size=256 --expose-gc"
      - key: DB_POOL_SIZE
        value: 1
      - key: MEMORY_WARNING_THRESHOLD
        value: 70
      - key: MEMORY_CRITICAL_THRESHOLD
        value: 85
    scaling:
      minInstances: 1
      maxInstances: 1
