services:
  - type: web
    name: ecommerce-backend
    env: node
    region: oregon # Choose closest region
    plan: standard # Upgrade for production
    buildCommand: |
      npm install
      npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://your-frontend.com
      - key: PORT
        value: 10000
      - key: SMTP_HOST # For email notifications
        sync: false
    healthCheckPath: /api/v1/health
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      cpuThreshold: 80
      memoryThreshold: 80